//
//  ESNewUnstakeRouter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 11.12.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ESNewUnstakeRoutingLogic {
    func unstake(amount: String)
    func back()
}

protocol ESNewUnstakeDataPassing {
    var dataStore: ESNewUnstakeDataStore? { get }
}

class ESNewUnstakeRouter: NSObject, ESNewUnstakeRoutingLogic, ESNewUnstakeDataPassing {
    
    weak var viewController: ESNewUnstakeViewController?
    var dataStore: ESNewUnstakeDataStore?

    func unstake(amount: String) {
        guard let validator = dataStore?.model  else { return }
        
        EverstakeSDK.shared.onAction?(.unstake, validator.symbol, amount,
                                    [ESValidatorInfo(name: validator.title, address: validator.address)])
        
    }
    
    func back() {
        viewController?.navigationController?.popViewController(animated: true)
    }
}
