//
//  ESNewUnstakePresenter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 11.12.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewUnstakePresentationLogic {
    func present(model: ESStakeCoinDetails.ViewModel.ValidatorStake)
}

class ESNewUnstakePresenter: ESNewUnstakePresentationLogic {
    weak var viewController: ESNewUnstakeDisplayLogic?
  
    func present(model: ESStakeCoinDetails.ViewModel.ValidatorStake) {
        let viewModel = ESNewUnstake.ViewModel(model: model)
        viewController?.display(viewModel: viewModel)
    }

}
