//
//  ESNewUnstakeInteractor.swift
//  Pods
//
//  Created by Alexander Koziaruk on 11.12.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewUnstakeBusinessLogic {
    func loadData()
}

protocol ESNewUnstakeDataStore {
    var model: ESStakeCoinDetails.ViewModel.ValidatorStake { get set }
}

class ESNewUnstakeInteractor: ESNewUnstakeBusinessLogic, ESNewUnstakeDataStore {
    var presenter: ESNewUnstakePresentationLogic?
    
    var model: ESStakeCoinDetails.ViewModel.ValidatorStake
    
    init(model: ESStakeCoinDetails.ViewModel.ValidatorStake) {
        self.model = model
    }
  
    func loadData() {
        presenter?.present(model: model)
    }
}
