//
//  ESNewUnstakeModels.swift
//  Pods
//
//  Created by Alexander Koziaruk on 11.12.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ESNewUnstake {
  
    class ViewModel {
        
        let stakedBalance: Double
        let symbol: String
        var amountToUnstake: Double
        
        init(model: ESStakeCoinDetails.ViewModel.ValidatorStake) {
            stakedBalance = Double(model.amount) ?? 0
            symbol = model.symbol.uppercased()
            
            amountToUnstake = 0
        }
        
        var displayStakedBalance: String {
            return stakedBalance.clean + " " + symbol
        }
    }
}
