//
//  ESCalculatorPresenter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 26.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESCalculatorPresentationLogic {
    func present(_ model: ESSharedModel.Combined, validator: ESSharedModel.Validator?)
}

class ESCalculatorPresenter: ESCalculatorPresentationLogic {
    weak var viewController: ESCalculatorDisplayLogic?
    
    func present(_ model: ESSharedModel.Combined, validator: ESSharedModel.Validator?) {
        let viewModel = ESCalculator.ViewModel(model: model,
                                               selectedValidator: validator)
        viewController?.display(newViewModel: viewModel)
    }

}
