//
//  ESCalculatorViewController.swift
//  Pods
//
//  Created by Alexander Koziaruk on 26.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESCalculatorDisplayLogic: class {
    func display(viewModel: ESCalculator.ViewModel)
}

class ESCalculatorViewController: UIViewController, ESCalculatorDisplayLogic {
    var interactor: ESCalculatorBusinessLogic?
    var router: (NSObjectProtocol & ESCalculatorRoutingLogic & ESCalculatorDataPassing)?

//MARK: Outlets

    @IBOutlet weak var amountTextField: UITextField!
    @IBOutlet weak var symbolLabel: UILabel!
    @IBOutlet weak var currencyValueLabel: UILabel!
    @IBOutlet weak var yearlyIncomeLabel: UILabel!
    @IBOutlet weak var validatorValueLabel: UILabel!
    @IBOutlet weak var feeLabel: UILabel!
    @IBOutlet weak var dailyIncomeValueLabel: UILabel!
    @IBOutlet weak var mounthlyIncomeValueLabel: UILabel!
    @IBOutlet weak var yearlyIncomeValueLabel: UILabel!
    
//MARK: Actions
    
    @IBAction func backButtonPressed() {
        navigationController?.popViewController(animated: true)
    }
    
    @IBAction func currencyButtonPressed() {
        router?.selectCurrency()
    }
    
    @IBAction func validatorButtonPressed() {
        router?.selectValidator()
    }
    
    @IBAction func proceedToStakingButtonPressed() {
        //TODO: open stake with current settings
    }
    
    @IBAction func reinvestEarningsSwitchValueChanged(_ sender: UISwitch) {
        //TODO: update calculation
    }
    
    @IBAction func includeValidatorFeeSwitchValueChanged(_ sender: UISwitch) {
        //TODO: update calculation
    }
    
    //Required by keyboard done button
    @objc func doneButtonAction() {
        amountTextField.resignFirstResponder()
        //TODO: update calculation
    }
    
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        amountTextField.addDoneButtonWith(width: view.frame.width,
                                          selector: #selector(ESCalculatorViewController.doneButtonAction))
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        interactor?.getData()
    }
    
    func display(viewModel: ESCalculator.ViewModel) {
        symbolLabel.text = viewModel.symbol
        validatorValueLabel.text = viewModel.validatorName
        yearlyIncomeLabel.text = viewModel.yearlyIncom
        currencyValueLabel.text = viewModel.currency
        feeLabel.text = viewModel.validatorFee
        feeLabel.isHidden = !viewModel.showFee
    }
    
}
