//
//  ESCalculatorModels.swift
//  Pods
//
//  Created by Alexander Koziaruk on 26.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ESCalculator {

// MARK: Use cases
  
    struct ViewModel {
        
        let symbol: String!
        let currency: String!
        let yearlyIncom: String!
        let validatorName: String!
        let validatorFee: String?
        let showFee: Bool
        
        init(model: ESSharedModel.Combined, selectedValidator: ESSharedModel.Validator?) {
            symbol = (model.coin.symbol ?? "").uppercased()
            currency = model.coin.name ?? ""
            yearlyIncom = "Yearly incom: " + (model.coin.apr ?? "") + "%"
            validatorName = selectedValidator?.name ?? ""
            showFee = !(selectedValidator?.fee != nil && selectedValidator!.fee == "0")
            validatorFee = "Fee: " + (selectedValidator?.fee ?? "") + "%"
        }
    }
}
