//
//  ESCalculatorInteractor.swift
//  Pods
//
//  Created by Alexander Koziaruk on 26.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESCalculatorBusinessLogic {
    func getData()
}

protocol ESCalculatorDataStore {
    var model: ESServerModel.Combined! { get set }
    var selectedValidator: ESServerModel.Validator? { get set }
}

class ESCalculatorInteractor: ESCalculatorBusinessLogic, ESCalculatorDataStore {
    var presenter: ESCalculatorPresentationLogic?
    var worker: ESCalculatorWorker?
    var model: ESServerModel.Combined! {
        didSet {
            selectedValidator = model.coin.validators?.first
        }
    }
    var selectedValidator: ESServerModel.Validator?
        
    func getData() {
        presenter?.present(model, validator: selectedValidator)
    }
  
}
