//
//  ESStakeCoinDetailsPresenter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 29.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESStakeCoinDetailsPresentationLogic {
    func present(_ coin: ESServerModel.Combined)
}

class ESStakeCoinDetailsPresenter: ESStakeCoinDetailsPresentationLogic {    
    weak var viewController: ESStakeCoinDetailsDisplayLogic?
  
// MARK: ESStakeCoinDetailsPresentationLogic
  
    func present(_ model: ESServerModel.Combined) {
        let viewModel = ESStakeCoinDetails.ViewModel(model: model)
        viewController?.updateWith(viewModel)
    }
    

}
