//
//  ESStakeCoinDetailsModels.swift
//  Pods
//
//  Created by Alexander Koziaruk on 29.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ESStakeCoinDetails {
  
    struct ViewModel {
        
        let title: String!
        let iconURL: URL!
        let apr: Int?
        
        init(model: ESSharedModel.Combined) {
            title = model.coin.name
            iconURL = model.coin.iconUrl
            apr = model.coin.apr
        }
        
        var displayApr: String {
           return "\(apr ?? 0)%"
        }
    }
}
