//
//  ESStakeCoinDetailsRouter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 29.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESStakeCoinDetailsRoutingLogic {
    func stakePressed()
    func unstakeValidator(_ validator: ESStakeCoinDetails.ViewModel.ValidatorStake)
}

protocol ESStakeCoinDetailsDataPassing {
    var dataStore: ESStakeCoinDetailsDataStore? { get }
}

class ESStakeCoinDetailsRouter: NSObject, ESStakeCoinDetailsRoutingLogic, ESStakeCoinDetailsDataPassing {
    
    weak var viewController: ESStakeCoinDetailsViewController?
    var dataStore: ESStakeCoinDetailsDataStore?

    // MARK: Routing

    func stakePressed()  {
        
        guard let model = dataStore?.model else { return }

        if model.stake == nil {
            routeToNewStakeWith(model)
        } else {
            viewController?.presentAlertWith(title: "Stake", message: "Please unstake your funds first.")
        }
    }
    
    func routeToNewStakeWith(_ model: ESSharedModel.Combined) {
        let newStakeViewController = ESNewStakeConfigurator.viewControllerWith(model)
        viewController?.navigationController?.pushViewController(newStakeViewController,
                                                                 animated: true)
    }
    
    func unstakeValidator(_ validator: ESStakeCoinDetails.ViewModel.ValidatorStake) {
        //TODO: complete ESStake model
        let stake = ESStake(symbol: validator.symbol)
        EverstakeSDK.shared.onUnstake?(stake)
    }
    
}
