//
//  ESStakeCoinDetailsModels.swift
//  Pods
//
//  Created by Alexander Koziaruk on 29.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ESStakeCoinDetails {
  
    struct ViewModel {
        
        let title: String!
        let iconURL: URL!
        let apr: String!
        let serviceFeeMin: String!
        let serviceFeeMax: String!
        let about: String!
        
        init(model: ESSharedModel.Combined) {
            title = model.coin.name
            iconURL = model.coin.iconUrl
            apr = model.coin.apr
            serviceFeeMin = model.coin.fee?.min ?? "0"
            serviceFeeMax = model.coin.fee?.max ?? "0"
            about = model.coin.about ?? ""
        }
        
        var displayApr: String {
            return apr + "%"
        }
        
        var displayServiceFee: String {
            if (serviceFeeMin == serviceFeeMax) {
                return serviceFeeMin + "%"
            } else {
                return serviceFeeMin + "-" + serviceFeeMax + "%"
            }
        }
    }
}
