//
//  ESNewStakeWorker.swift
//  Pods
//
//  Created by Alex Koziaruk on 04.11.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ESNewStakeWorker {
    func doSomeWork() {
    }
}
