//
//  ESNewStakePresenter.swift
//  Pods
//
//  Created by Alex Koziaruk on 04.11.2020.
//  Copyright (c) 2020 Noisy Miner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewStakePresentationLogic {
    func present(_ model: ESServerModel.Combined,
                 selectedValidators: [ESServerModel.Validator],
                 prefilledAmount: Double?)
}

class ESNewStakePresenter: ESNewStakePresentationLogic {

    weak var viewController: ESNewStakeDisplayLogic?
    
    func present(_ model: ESServerModel.Combined,
                 selectedValidators: [ESServerModel.Validator],
                 prefilledAmount: Double?) {
        
        let viewModel = ESNewStake.ViewModel(model: model,
                                             selectedValidators: selectedValidators,
                                             amount: prefilledAmount)
        viewController?.display(viewModel: viewModel)
    }
    
}
