//
//  ESNewStakeViewController.swift
//  Pods
//
//  Created by Alexander Koziaruk on 04.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewStakeDisplayLogic: class {
    func displaySomething(viewModel: ESNewStake.Something.ViewModel)
}

class ESNewStakeViewController: UIViewController, ESNewStakeDisplayLogic {
    var interactor: ESNewStakeBusinessLogic?
    var router: (NSObjectProtocol & ESNewStakeRoutingLogic & ESNewStakeDataPassing)?

    
//MARK: Outlets
  
    @IBOutlet weak var yearlyIncomValueLabel: UILabel!
    @IBOutlet weak var balanceValueLabel: UILabel!
    @IBOutlet weak var amountTextField: UITextField!
    @IBOutlet weak var symbolLabel: UILabel!
    @IBOutlet weak var validatorNameLabel: UILabel!
    @IBOutlet weak var feeLabel: UILabel!
    @IBOutlet weak var reliableContainer: UIView!
    @IBOutlet weak var dailyIncomeValueLabel: UILabel!
    @IBOutlet weak var monthlyValueLabel: UILabel!
    @IBOutlet weak var yearlyValueLabel: UILabel!
    
    
//MARK: Actions
    
    @IBAction func stakeButtonPressed() {
        
    }
    
// MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
    func doSomething() {
        let request = ESNewStake.Something.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: ESNewStake.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
