//
//  ESNewStakePresenter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 04.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewStakePresentationLogic {
    func present(_ model: ESSharedModel.Combined,
                 selectedValidators: [ESSharedModel.Coin.Validator])
}

class ESNewStakePresenter: ESNewStakePresentationLogic {

    weak var viewController: ESNewStakeDisplayLogic?
    
    func present(_ model: ESSharedModel.Combined,
                 selectedValidators: [ESSharedModel.Coin.Validator]) {
        let viewModel = ESNewStake.ViewModel(model: model,
                                             selectedValidators: selectedValidators)
        viewController?.display(viewModel: viewModel)
    }
    
}
