//
//  ESNewStakePresenter.swift
//  Pods
//
//  Created by Alexander Koziaruk on 04.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ESNewStakePresentationLogic {
    func presentSomething(response: ESNewStake.Something.Response)
}

class ESNewStakePresenter: ESNewStakePresentationLogic {
    weak var viewController: ESNewStakeDisplayLogic?
  
// MARK: Do something
  
    func presentSomething(response: ESNewStake.Something.Response) {
        let viewModel = ESNewStake.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
